-- Lista inicial de palavras bloqueadas (pt-BR + en).
--
-- A tabela existia, a RLS existia, o filtro rodava em todo post/comentario/
-- mural/chat — e estava com ZERO linhas, entao nao bloqueava nada. Isto
-- popula a lista pela primeira vez.
--
-- COMO A SEVERIDADE FUNCIONA (ver src/lib/wordlist.js):
--   high    -> BARRA o envio. So o que nunca e aceitavel aqui.
--   medium  -> NAO barra. Passa e fica por conta da IA e das denuncias.
--
-- Por que palavrao comum e `medium` e nao `high`: numa comunidade gamer
-- "caralho que jogo foda" e elogio — a propria IA pontua isso em 0.066.
-- Barrar o envio por isso afastaria o usuario a toa. A IA julga contexto,
-- uma lista de palavras nao.
--
-- O match e por PALAVRA INTEIRA e SENSIVEL A ACENTO, por isso as variantes
-- acentuadas e sem acento entram como entradas separadas.
--
-- O dono edita, adiciona e remove qualquer entrada pelo painel:
-- Admin -> Moderacao -> Wordlist.

insert into public.blocked_words (word, severity)
select v.word, v.severity
from (values
  ('boiola','high'),
  ('baitola','high'),
  ('traveco','high'),
  ('travecos','high'),
  ('viadinho','high'),
  ('viadinhos','high'),
  ('viadao','high'),
  ('viadão','high'),
  ('crioulo','high'),
  ('criolo','high'),
  ('preto imundo','high'),
  ('negro imundo','high'),
  ('volta pra senzala','high'),
  ('macaco fedido','high'),
  ('nigger','high'),
  ('niggers','high'),
  ('nigga','high'),
  ('niggas','high'),
  ('chink','high'),
  ('spic','high'),
  ('kike','high'),
  ('wetback','high'),
  ('retardado','high'),
  ('retardada','high'),
  ('retardados','high'),
  ('mongoloide','high'),
  ('mongolóide','high'),
  ('debil mental','high'),
  ('débil mental','high'),
  ('retard','high'),
  ('retarded','high'),
  ('faggot','high'),
  ('faggots','high'),
  ('fag','high'),
  ('fags','high'),
  ('tranny','high'),
  ('trannies','high'),
  ('dyke','high'),
  ('kys','high'),
  ('kill yourself','high'),
  ('vai se matar','high'),
  ('va se matar','high'),
  ('vá se matar','high'),
  ('pedofilia','high'),
  ('pedofilo','high'),
  ('pedófilo','high'),
  ('pedofila','high'),
  ('pedófila','high'),
  ('pornografia infantil','high'),
  ('child porn','high'),
  ('childporn','high'),
  ('lolicon','high'),
  ('shotacon','high'),
  ('novinha nua','high'),
  ('novinhas nuas','high'),
  ('menor de idade nua','high'),
  ('cp infantil','high'),
  ('nudes','high'),
  ('nude','high'),
  ('nud3s','high'),
  ('manda nudes','high'),
  ('mando nudes','high'),
  ('troca de nudes','high'),
  ('pack de nudes','high'),
  ('vendo pack','high'),
  ('vendo nudes','high'),
  ('pack +18','high'),
  ('packs +18','high'),
  ('zoofilia','high'),
  ('necrofilia','high'),
  ('buceta','high'),
  ('bucetas','high'),
  ('xoxota','high'),
  ('boquete','high'),
  ('punheta','high'),
  ('siririca','high'),
  ('gozada','high'),
  ('pornografia','high'),
  ('pornô','high'),
  ('porno','high'),
  ('pornos','high'),
  ('p0rn','high'),
  ('pr0n','high'),
  ('hentai','high'),
  ('xvideos','high'),
  ('pornhub','high'),
  ('xnxx','high'),
  ('redtube','high'),
  ('brazzers','high'),
  ('onlyfans','high'),
  ('sexo explicito','high'),
  ('sexo explícito','high'),
  ('garota de programa','high'),
  ('gp de luxo','high'),
  ('caralho','medium'),
  ('caralhos','medium'),
  ('krl','medium'),
  ('crl','medium'),
  ('porra','medium'),
  ('poha','medium'),
  ('foda','medium'),
  ('foder','medium'),
  ('fodido','medium'),
  ('fodida','medium'),
  ('merda','medium'),
  ('bosta','medium'),
  ('puta','medium'),
  ('putas','medium'),
  ('putaria','medium'),
  ('cuzao','medium'),
  ('cuzão','medium'),
  ('arrombado','medium'),
  ('arrombada','medium'),
  ('otario','medium'),
  ('otário','medium'),
  ('babaca','medium'),
  ('escroto','medium'),
  ('escrota','medium'),
  ('desgracado','medium'),
  ('desgraçado','medium'),
  ('filho da puta','medium'),
  ('filha da puta','medium'),
  ('fdp','medium'),
  ('pqp','medium'),
  ('vsf','medium'),
  ('vtnc','medium'),
  ('tnc','medium'),
  ('vagabundo','medium'),
  ('vagabunda','medium'),
  ('corno','medium'),
  ('corna','medium'),
  ('imbecil','medium'),
  ('cretino','medium'),
  ('pilantra','medium'),
  ('fuck','medium'),
  ('fucking','medium'),
  ('fucker','medium'),
  ('motherfucker','medium'),
  ('shit','medium'),
  ('bullshit','medium'),
  ('bitch','medium'),
  ('bitches','medium'),
  ('asshole','medium'),
  ('bastard','medium'),
  ('cunt','medium'),
  ('dumbass','medium'),
  ('jackass','medium'),
  ('viado','medium'),
  ('veado','medium'),
  ('bicha','medium'),
  ('sapatao','medium'),
  ('sapatão','medium'),
  ('macaco','medium'),
  ('traveca','medium'),
  ('gay de merda','medium'),
  ('noob de merda','medium'),
  ('lixo de player','medium'),
  ('mata se','medium'),
  ('se mata','medium'),
  ('conteudo adulto','medium'),
  ('conteúdo adulto','medium')
) as v(word, severity)
where not exists (
  select 1 from public.blocked_words b where lower(b.word) = lower(v.word)
);;
